# -*- coding: utf-8 -*-
"""KG_Query-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjJdcZ_5MR-JSGp30kxfYwddCDPtyZim
"""

import os
import pandas as pd
from pathlib import Path

# ✅ Set data and output paths relative to notebook
NOTEBOOK_DIR = Path.cwd()
DATA_DIR = NOTEBOOK_DIR.parents[2] / "data" / "data" / "primekg"
OUTPUT_DIR = NOTEBOOK_DIR / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)

# ✅ Confirm data path
print("🔧 Data path resolved to:", DATA_DIR)
try:
    print("📂 Files in data path:", list(DATA_DIR.iterdir()))
except Exception as e:
    print("❌ Could not list data path:", e)

# ✅ Files and Labels
files = {
    "README.txt": "📘 README",
    "nodes.csv": "🧠 Nodes",
    "kg.csv": "📊 KG",
    "kg_raw.csv": "📊 KG Raw",
    "kg_grouped.csv": "📦 KG Grouped",
    "kg_grouped_diseases.csv": "🧬 KG Grouped Diseases",
    "kg_grouped_diseases_bert_map.csv": "🧬 KG Diseases BERT Map",
    "kg.giant.csv": "🗺️ KG Giant",
    "edges.csv": "🔗 Edges",
    "drug_features.csv": "💊 Drug Features",
    "disease_features.csv": "🦠 Disease Features"
}

# ✅ Load and preview files
for file, label in files.items():
    full_path = DATA_DIR / file
    print(f"\n--- {label} ({file}) ---")
    try:
        if file.endswith(".txt"):
            print(full_path.read_text().strip()[:1000])
        else:
            df = pd.read_csv(full_path)
            print(df.head())
    except Exception as e:
        print(f"❌ Failed to load {file}: {e}")

import pandas as pd
from pathlib import Path

# === Set base path to current notebook directory ===
NOTEBOOK_DIR = Path.cwd()
DATA_DIR = NOTEBOOK_DIR.parents[2] / "data" / "data" / "primekg"


# === Required CSVs ===
required_files = [
    "disease_features.csv",
    "kg.csv",
    "nodes.csv",
    "drug_features.csv"
]

# === Check if files exist ===
missing = [f for f in required_files if not (DATA_DIR / f).exists()]
if missing:
    print(f"❌ Missing required files: {missing}")
    print(f"   ➤ Please place them inside: {DATA_DIR.resolve()}")
else:
    print(f"✅ All required files found in: {DATA_DIR.resolve()}")

# === Load Data ===
if not missing:
    disease_feat = pd.read_csv(DATA_DIR / "disease_features.csv")
    kg = pd.read_csv(DATA_DIR / "kg.csv")
    nodes = pd.read_csv(DATA_DIR / "nodes.csv")
    drug_feat = pd.read_csv(DATA_DIR / "drug_features.csv")
    print("📥 Files loaded successfully.")

# === 1. Search for 'osteogenesis imperfecta' ===
term = "osteogenesis imperfecta"

mask = (
    disease_feat['mondo_name'].str.contains(term, case=False, na=False) |
    disease_feat['umls_description'].str.contains(term, case=False, na=False) |
    disease_feat['orphanet_definition'].str.contains(term, case=False, na=False)
)
match = disease_feat[mask]

if match.empty:
    print(f"❌ No disease entry found for '{term}'.")
    exit()

print(f"✅ Found {len(match)} entries for '{term}'.")

# === 2. Get node index ===
indices = match['node_index'].unique().tolist()
print(f"Node indices for '{term}': {indices}")

# === 3. Find edges ===
assoc_edges = kg[(kg['x_index'].isin(indices)) | (kg['y_index'].isin(indices))]
print(f"✅ Found {len(assoc_edges)} edges connected to '{term}'.")

# === 4. Get all other node indices ===
assoc_node_indices = set(pd.concat([assoc_edges['x_index'], assoc_edges['y_index']])) - set(indices)

# === 5. Get associated node details ===
assoc_nodes = nodes[nodes['node_index'].isin(assoc_node_indices)]

# === 6. Show drugs ===
drugs = assoc_nodes[assoc_nodes['node_type'] == 'drug']
if not drugs.empty:
    drugs_with_desc = drugs.merge(drug_feat, on='node_index', how='left')
    print("\n💊 Drugs associated:")
    print(drugs_with_desc[['node_name', 'description', 'indication']])
else:
    print("\nℹ️ No drugs associated.")

# === 7. Show genes/proteins ===
genes = assoc_nodes[assoc_nodes['node_type'] == 'gene/protein']
if not genes.empty:
    print("\n🧬 Genes/Proteins associated:")
    print(genes[['node_name']])
else:
    print("\nℹ️ No genes/proteins associated.")

# === 8. Disease details ===
print("\n📝 Disease details:")
with pd.option_context('display.max_colwidth', 500):
    print(match.T)

import pandas as pd
from pathlib import Path

def main():
    # === CONFIG ===
    NOTEBOOK_DIR = Path.cwd()
    DATA_DIR = NOTEBOOK_DIR.parents[2] / "data" / "data" / "primekg"

    # === Required files ===
    required_files = [
        "kg.csv",
        "nodes.csv",
        "drug_features.csv",
        "disease_features.csv"
    ]

    # === Check all files exist ===
    missing = [f for f in required_files if not (DATA_DIR / f).exists()]
    if missing:
        print(f"❌ Missing files: {missing}")
        print(f"👉 Please make sure these files are in: {DATA_DIR.resolve()}")
        return

    # === 1. Load data ===
    kg = pd.read_csv(DATA_DIR / "kg.csv")
    nodes = pd.read_csv(DATA_DIR / "nodes.csv")
    drug_feat = pd.read_csv(DATA_DIR / "drug_features.csv")
    disease_feat = pd.read_csv(DATA_DIR / "disease_features.csv")

    # === 2. Drug search term ===
    search_term = "aspirin"  # <<-- change to your drug name!

    # === 3. Find drug nodes ===
    drug_matches = nodes[
        (nodes['node_type'] == 'drug') &
        (nodes['node_name'].str.contains(search_term, case=False, na=False))
    ]

    if drug_matches.empty:
        print(f"❌ No drug entry for '{search_term}' found.")
        return

    drug_indices = drug_matches['node_index'].unique().tolist()
    print(f"\n✅ Found drug node indices: {drug_indices}")

    # === 4. Find edges connected to the drug ===
    assoc_edges = kg[
        (kg['x_index'].isin(drug_indices)) | (kg['y_index'].isin(drug_indices))
    ]
    print(f"✅ Found {len(assoc_edges)} associations for '{search_term}'.")

    # === 5. Get other connected nodes ===
    assoc_node_indices = set(pd.concat([assoc_edges['x_index'], assoc_edges['y_index']])) - set(drug_indices)
    assoc_nodes = nodes[nodes['node_index'].isin(assoc_node_indices)]

    # === 6. Connected diseases ===
    diseases = assoc_nodes[assoc_nodes['node_type'] == 'disease']
    if not diseases.empty:
        diseases_with_desc = diseases.merge(disease_feat, on='node_index', how='left')
        print("\n🦠 Diseases connected to this drug:")
        with pd.option_context('display.max_colwidth', 1000):
            print(diseases_with_desc[['node_name', 'mondo_definition', 'umls_description']])
    else:
        print("\nℹ️ No diseases connected.")

    # === 7. Connected genes/proteins ===
    genes = assoc_nodes[assoc_nodes['node_type'] == 'gene/protein']
    if not genes.empty:
        print("\n🧬 Genes/proteins connected to this drug:")
        print(genes[['node_name']])
    else:
        print("\nℹ️ No genes/proteins connected.")

    # === 8. Connected other drugs ===
    other_drugs = assoc_nodes[assoc_nodes['node_type'] == 'drug']
    if not other_drugs.empty:
        other_drugs_desc = other_drugs.merge(drug_feat, on='node_index', how='left')
        print("\n💊 Other drugs connected to this drug:")
        print(other_drugs_desc[['node_name', 'description', 'indication']])
    else:
        print("\nℹ️ No other drugs connected.")

    # === 9. Show details for the searched drug ===
    drug_details = drug_matches.merge(drug_feat, on='node_index', how='left')
    print("\n🔎 Details for the searched drug:")
    with pd.option_context('display.max_colwidth', 1000):
        print(drug_details.T)

if __name__ == "__main__":
    main()

import pandas as pd
from pathlib import Path

def main():
    # === CONFIG ===
    NOTEBOOK_DIR = Path.cwd()
    DATA_DIR = NOTEBOOK_DIR.parents[2] / "Code" / "data" / "primekg"

    # === Required files ===
    required_files = [
        "kg.csv",
        "nodes.csv",
        "drug_features.csv",
        "disease_features.csv"
    ]

    # === Check all files exist ===
    missing = [f for f in required_files if not (DATA_DIR / f).exists()]
    if missing:
        print(f"❌ Missing files: {missing}")
        print(f"👉 Please make sure these files are in: {DATA_DIR.resolve()}")
        return

    # === 1. Load data ===
    kg = pd.read_csv(DATA_DIR / "kg.csv")
    nodes = pd.read_csv(DATA_DIR / "nodes.csv")
    drug_feat = pd.read_csv(DATA_DIR / "drug_features.csv")
    disease_feat = pd.read_csv(DATA_DIR / "disease_features.csv")

    # === 2. Set your search term ===
    search_term = "BRCA1"  # 👈 change this to your gene/protein name

    # === 3. Find gene/protein node(s) ===
    gene_matches = nodes[
        (nodes['node_type'] == 'gene/protein') &
        (nodes['node_name'].str.contains(search_term, case=False, na=False))
    ]

    if gene_matches.empty:
        print(f"❌ No gene/protein entry found for '{search_term}'.")
        return

    gene_indices = gene_matches['node_index'].unique().tolist()
    print(f"\n✅ Found gene/protein node indices: {gene_indices}")

    # === 4. Find edges ===
    assoc_edges = kg[
        (kg['x_index'].isin(gene_indices)) | (kg['y_index'].isin(gene_indices))
    ]
    print(f"✅ Found {len(assoc_edges)} associations for '{search_term}'.")

    # === 5. Get other connected nodes ===
    assoc_node_indices = set(pd.concat([assoc_edges['x_index'], assoc_edges['y_index']])) - set(gene_indices)
    assoc_nodes = nodes[nodes['node_index'].isin(assoc_node_indices)]

    # === 6. Connected diseases ===
    diseases = assoc_nodes[assoc_nodes['node_type'] == 'disease']
    if not diseases.empty:
        diseases_with_desc = diseases.merge(disease_feat, on='node_index', how='left')
        print("\n🦠 Diseases connected to this gene/protein:")
        with pd.option_context('display.max_colwidth', 1000):
            print(diseases_with_desc[['node_name', 'mondo_definition', 'umls_description']])
    else:
        print("\nℹ️ No diseases connected.")

    # === 7. Connected drugs ===
    drugs = assoc_nodes[assoc_nodes['node_type'] == 'drug']
    if not drugs.empty:
        drugs_with_desc = drugs.merge(drug_feat, on='node_index', how='left')
        print("\n💊 Drugs connected to this gene/protein:")
        print(drugs_with_desc[['node_name', 'description', 'indication']])
    else:
        print("\nℹ️ No drugs connected.")

    # === 8. Connected other genes/proteins ===
    other_genes = assoc_nodes[assoc_nodes['node_type'] == 'gene/protein']
    if not other_genes.empty:
        print("\n🧬 Other genes/proteins connected to this gene/protein:")
        print(other_genes[['node_name']])
    else:
        print("\nℹ️ No other genes/proteins connected.")

    # === 9. Show details for the searched gene/protein ===
    print("\n🔎 Details for the searched gene/protein:")
    with pd.option_context('display.max_colwidth', 1000):
        print(gene_matches.T)

if __name__ == "__main__":
    main()